<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"
  xmlns:s="http://maven.apache.org/supplemental-model/1.0.0">

  <!--
    $Id: supplemental-models-to-3rdparty.xsl 8881 2014-09-04 16:02:56Z birkland $
    $URL: https://scm.dataconservancy.org/svn/maven/project/trunk/supplemental-resources/src/main/resources/supplemental-models-to-3rdparty.xsl $
    
    This stylesheet transforms the Maven Remote Resources Plugin supplemental model to the 
    Codehaus licenses model.
    
    The MRRP supplemental model is serialized in the supplemental-models.xml file, and more
    information on its format is at http://maven.apache.org/plugins/maven-remote-resources-plugin/supplemental-models.html
    
    The Codeaus licences model is serialized in the src/license/THIRD-PARTY.properties file, and more information
    on its format is at http://mojo.codehaus.org/license-maven-plugin/examples/example-thirdparty.html
  -->

  <xsl:output  xml:space="preserve" indent="no" version="1.0" media-type="text/plain" encoding="UTF-8" method="text"/>

  <xsl:template match="/">
<xsl:text>#  
# Generated by transforming supplemental-models.xml (found in org.dataconservancy:supplemental-resources) with $Id: supplemental-models-to-3rdparty.xsl 8881 2014-09-04 16:02:56Z birkland $
# found at $URL: https://scm.dataconservancy.org/svn/maven/project/trunk/supplemental-resources/src/main/resources/supplemental-models-to-3rdparty.xsl $
#
</xsl:text>

      <xsl:apply-templates select="//s:project"/>
  </xsl:template>

  <xsl:template match="//s:project">
    <xsl:if test="s:licenses/s:license">
        <xsl:variable name="foo"><xsl:value-of select="s:groupId"/><xsl:text>--</xsl:text><xsl:value-of select="s:artifactId"/><xsl:text>--</xsl:text><xsl:value-of select="s:version"/><xsl:text>=</xsl:text></xsl:variable>
        <xsl:for-each select="s:licenses/s:license">
            <xsl:if test="s:name">
<xsl:value-of select="$foo"/><xsl:value-of select="s:name"/><xsl:text>
</xsl:text>
            </xsl:if>
        </xsl:for-each>
    </xsl:if>
  </xsl:template>

</xsl:stylesheet>
